name = "gwern-rss"
main = "src/index.ts"
compatibility_date = "2025-12-27"
account_id = "3dc1944c1aabdb20168d6c12fc23abd1"

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "KV"
id = "c586e19b7bcf4225b452c6cdb182a601"

[[routes]]
pattern = "gwern-rss.marx.sh/*"
zone_name = "marx.sh"
